name: Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza a animação diariamente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a animação Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Commit e Push da animação
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git add -A
          git commit -m "Gerado snake animation" || exit 0
          git push
